# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
loom_version=1.14.1
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.18.4

# Mod Properties
mod_version=2.1.0
maven_group=dev.persn
archives_base_name=wdmgslt
# wdmgslt = Why Does My Glass Sound Like That

# Dependencies
fabric_version=0.140.2+1.21.11
